# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui9.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Name(object):
    def setupUi(self, Name):
        Name.setObjectName("Name")
        Name.resize(900, 600)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(14)
        Name.setFont(font)
        self.centralwidget = QtWidgets.QWidget(Name)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(21, 20, 861, 501))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setMinimumSize(QtCore.QSize(800, 100))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 10, 781, 81))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.frame, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.frame_2 = QtWidgets.QFrame(self.widget)
        self.frame_2.setMinimumSize(QtCore.QSize(800, 100))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.nameEdit = QtWidgets.QLineEdit(self.frame_2)
        self.nameEdit.setGeometry(QtCore.QRect(10, 30, 781, 41))
        self.nameEdit.setObjectName("nameEdit")
        self.verticalLayout.addWidget(self.frame_2, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.btn_frame = QtWidgets.QFrame(self.widget)
        self.btn_frame.setMinimumSize(QtCore.QSize(420, 60))
        self.btn_frame.setMaximumSize(QtCore.QSize(16777215, 200))
        self.btn_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.btn_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.btn_frame.setObjectName("btn_frame")
        self.start_button = QtWidgets.QPushButton(self.btn_frame)
        self.start_button.setGeometry(QtCore.QRect(220, 0, 200, 60))
        self.start_button.setMaximumSize(QtCore.QSize(200, 60))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.start_button.setFont(font)
        self.start_button.setObjectName("start_button")
        self.back_button = QtWidgets.QPushButton(self.btn_frame)
        self.back_button.setGeometry(QtCore.QRect(0, 0, 200, 60))
        self.back_button.setMaximumSize(QtCore.QSize(200, 60))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.back_button.setFont(font)
        self.back_button.setObjectName("back_button")
        self.verticalLayout.addWidget(self.btn_frame, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        Name.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Name)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 34))
        self.menubar.setObjectName("menubar")
        Name.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Name)
        self.statusbar.setObjectName("statusbar")
        Name.setStatusBar(self.statusbar)

        self.retranslateUi(Name)
        QtCore.QMetaObject.connectSlotsByName(Name)

    def retranslateUi(self, Name):
        _translate = QtCore.QCoreApplication.translate
        Name.setWindowTitle(_translate("Name", "Имя пользователя"))
        self.label.setText(_translate("Name", "Введите Ваше имя"))
        self.start_button.setText(_translate("Name", "Начать"))
        self.back_button.setText(_translate("Name", "Вернуться"))
